name: Backend Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore dotNet/TokoApi.Tests/TokoApi.Tests.csproj

    - name: Verify Docker is available
      run: docker info

    - name: Run xUnit & Testcontainers
      run: dotnet test dotNet/TokoApi.Tests/TokoApi.Tests.csproj --verbosity normal --no-restore
